[project]
name = "scrape-chatgpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "wreq>=0.12.1",
]

[project.scripts]
scrape-chatgpt = "scrape_chatgpt:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
